# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TempDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Charts'
  # Pods for TempDemo

  target 'TempDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
